import "@/app/styles/globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Header } from "@/components/Header";
import { promises as fs } from "fs";
import path from "path";
import { Footer } from "@/components/Footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://smakshine.vercel.app"),
  alternates: {
    canonical: "/",
  },
  title: {
    default: "SmakShine — Ванильный РП Сервер",
    template: "%s | SmakShine",
  },
  description: "Generated by create next app",
  keywords: ["minecraft", "rp", "private server", "minecraft server"],
  icons: {
    icon: [{ url: "/rounded-icon.svg", type: "image/svg" }],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seasonsDir = path.join(process.cwd(), "content", "seasons");
  const files = await fs.readdir(seasonsDir);

  const seasonLinks = files
    .filter((f) => f.endsWith(".mdx"))
    .map((f) => {
      const id = f.replace(".mdx", "");
      return {
        name: `Сезон ${id}`,
        href: `/seasons/${id}`,
      };
    });

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manrope.className} flex min-h-screen flex-col`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <Header seasonLinks={seasonLinks} />
          <main className="flex-grow">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
